config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :sessions => "sessions" }
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "posts/maxshow" => 'posts#maxshow', :as => :maxshow
    end
    collection do 
      get :register_info
    end
    resources :comments
  end

  resources :dashboard, only: [:index, :show]

  root "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
  acts_as_taggable
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { maxlarge: "800x600>", large: "800x600#", medium: "400x300#", thumb: "200x150#", attach: "126x95#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	
  	has_many :impressions, :as=>:impressionable

  	def impression_count
    	impressions.size
  	end

  	def unique_impression_count
    	impressions.group(:ip_address).size #UNTESTED: might not be correct syntax
      #impressionist_count(:filter=>:ip_address).size
      #impressionist_count(:filter=>:session_hash)
      #impressionist_count :unique => [:impressionable_type, :impressionable_id, :session_hash]
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :profile, styles: { medium: "80x80#", thumb: "48x48#", small: "32x32#", xsmall: "18x18#", xssmall: "16x16#" }
  validates_attachment_content_type :profile, content_type: /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :name, :password, :password_confirmation, :current_password, :profile) }
  	devise_parameter_sanitizer.for(:account_update) { |n| n.permit(:email, :name, :password, :password_confirmation, :current_password, :profile, :location, :website, :bio, :twitter, :facebook, :github, :instagram, :cm) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController 
	before_action :authenticate_user!, except: [:show]

	def show
		@user = User.find_by_id(params[:id])
		@posts = @user.posts.order("title asc").paginate(:page => params[:page], :per_page => 50)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :log_impression, :maxshow]
	before_action :authenticate_user!, except: [:index, :show, :register_info, :maxshow]
	before_filter :log_impression, only: [:show]

	layout false, only: [:maxshow]

	def index
		if params[:tag]
			@posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 20)
		else
			@posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 20)
		end
		@uposts = Post.all.order("user_id desc").limit(4)
	end

	def show
		@comments = Comment.where(post_id: @post)
		@random_posts = Post.all.where(user_id: @post.user.id).where.not(id: @post.id).order("created_at").limit(4)
	end

	def new
		#@post = Post.new
		@post = current_user.posts.build
	end
	## save file to databases
	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		
	end
	## update a file
	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def log_impression
		if user_signed_in?
			@post.impressions.create(ip_address: request.remote_ip, user_id:current_user.id)
		else
			@post.impressions.create(ip_address: request.remote_ip)
		end
	end

	def register_info
		
	end

	def maxshow
		respond_to do |format|
			format.html
			format.js
		end
	end

	private

	def post_params
		params.require(:post).permit(:title, :link, :description, :image, :attach, :tag_list)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout false
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :content, class: "txt-area", label: false
	= f.button :submit, "Comment", class: "btn-com"

app/views/dashboard/show.html.erb
<div class="categories xddf">
	<div class="container-fluid">
		<ul class="nav navbar-nav pull-left popo">
			<li>
				<%= link_to dashboard_path(@user) do %>
					<%= @posts.count %> <span>Shots</span>
				<% end %>
			</li>
			<li>
				<a href="#">20 <span>Project</span></a>
			</li>
			<li>
				<a href="#">189.090 <span>Followers</span></a>
			</li>
			<li>
				<a href="#" class="mre"><span>More</span></a>
			</li>
		</ul>
		<% if current_user != @user %>
			<ul class="nav navbar-nav pull-right pipi">
				<li>
					<a href="#" class="btd btd1">Hire Me</a>
				</li>
				<li>
					<a href="#" class="btd btd2">Following</a>
				</li>
			</ul>
		<% end %>
	</div>
</div>
<div class="container-fluid">
	<div class="gehd">
		<%= link_to (image_tag @user.profile.url(:medium), class: "img-pros"), dashboard_path(@user) %>
		<h3><%= @user.name %></h3>
		<p><%= @user.location %></p>
		<h4><%= @user.bio %></h4>
		<div class="sos">
			<ul class="list-inline vbghj">
				<% unless @user.twitter.blank? %>
					<li>
						<a href="<%= @user.twitter %>" class="twitter"><i class="fa fa-twitter"></i></a>
					</li>
				<% end %>
				<% unless @user.facebook.blank? %>
					<li>
						<a href="<%= @user.facebook %>" class="fb"><i class="fa fa-facebook-official"></i></a>
					</li>
				<% end %>
				<% unless @user.instagram.blank? %>
					<li>
						<a href="<%= @user.instagram %>" class="instag"><i class="fa fa-instagram"></i></a>
					</li>
				<% end %>
				<% unless @user.github.blank? %>
					<li>
						<a href="<%= @user.github %>" class="git"><i class="fa fa-github"></i></a>
					</li>
				<% end %>
				<% unless @user.cm.blank? %>
					<li>
						<a href="<%= @user.cm %>" class="cm"><i class="fa fa-diamond"></i></a>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>
<div class="main-content">
	<div class="container-fluid cf2">
		<div class="row">
			<% @posts.each do |post| %>
				<div class="col-sm-6 col-md-2 frm tmk">
					<div class="thumbnail tmbl">
						<div class="img-co">
							<%= link_to (image_tag post.image.url(:thumb)), post %>
						</div>
						<ul class="list-inline pull-right">
							<li>
								<span class="like"><%= post.get_upvotes.size %></span>
							</li>
							<li>
								<span class="comm"><%= post.comments.count %></span>
							</li>
							<li>
								<span class="view"><%= post.impression_count %></span>
							</li>
						</ul>
						<% if post.attach? %>
						<ul class="list-inline pull-left">
							<li>
								<span class="att"></span>
							</li>
						</ul>
						<% end %>
						<div class="clear"></div>
					</div>
					<%= link_to(post_path(post)) do %>
						<div class="hov">
							<div class="cons">
								<span class="title"><%= truncate(post.title, length: 20) %></span>
								<p class="cox"><%= truncate(post.description, length: 90) %></p>
								<span class="date"><%= post.created_at.strftime('%B %e, %G') %></span>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="cf">
		<%= will_paginate @posts %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dribclone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<%= link_to (image_tag "logo/logo.png", class: "navbar-brand"), root_path %>
			</div>
			<ul class="nav navbar-nav">
				<li><a href="#">Shots</a></li>
				<li><a href="#">Designers</a></li>
				<li><a href="#">Teams</a></li>
				<li><a href="#">Stories</a></li>
				<li><a href="#">Meetups</a></li>
				<li><a href="#">Shop</a></li>
				<li><a href="#">Jobs</a></li>
				<li><a href="#"><%= image_tag "dot.png", class: "kokd" %></a></li>
			</ul>
			<form class="navbar-form navbar-right" role="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
			</form>
			<ul class="nav navbar-nav navbar-right df">
				<% if user_signed_in? %>
					<li class="dropdown">
						<a  href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" >
							<% if current_user.profile? %>
								<%= image_tag current_user.profile.url(:xsmall) %>
							<% else %>
								<%= image_tag "logo/ava.gif", class: "ckl" %>
							<% end %>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to current_user.name, dashboard_path(current_user.id) %></li>
							<hr class="div">
							<li><a href="#" class="go">GoPro</a></li>
							<li><%= link_to "Shots", new_post_path %></li>
							<hr class="div">
							<li><%= link_to "Account Settings", edit_user_registration_path %></li>
							<li><%= link_to "Sign out", destroy_user_session_path, method: :delete  %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Sign up", register_info_posts_path %></li>
					<li><%= link_to "Sign in", new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</nav>
<%= yield %>
<footer>
	<div class="container-fluid">
		<div class="top-foot">
			<div class="col-md-3 frs-side">
				<div class="logo">
					<%= link_to (image_tag "logo/lgo.png", class: "ft-img"), root_path %>
				</div>
				<div class="tst">
					<h5>Show and tell for designers</h5>
					<p>What are you working on? Dribbble is a community of designers sharing screenshots of their work, process, and projects.</p>
				</div>
			</div>
			<div class="col-md-4 scd-side">
				<div class="col-md-3">
					<ul>
						<li>
							<a href="#">About</a>
						</li>
						<li><a href="#">Help</a></li>
						<li>
							<a href="#">Contact</a>
						</li>
						<li>
							<a href="#">Terms</a>
						</li>
					</ul>
				</div>
				<div class="col-md-3">
					<ul>
						<li><a href="#">Privacy</a></li>
						<li><a href="#">Shop</a></li>
						<li><a href="#">Testimonial</a></li>
						<li><a href="#">Handbook</a></li>
					</ul>
				</div>
				<div class="col-md-3">
					<ul>
						<li><a href="#">Brand</a></li>
						<li><a href="#">Advertise</a></li>
						<li><a href="#">API</a></li>
						<li><a href="#">Integrations</a></li>
					</ul>
				</div>
			</div>
			<div class="col-md-4 trd-side">
				<div class="ti">
					<h5>Jobs for Designers</h5>
				</div>
				<ul>
					<li>
						<div class="col-md-3">
							<%= link_to (image_tag "logo/ldf.png"), root_path %>
						</div>
						<div class="col-md-9">
							<p>Quartzy</p>
							<span>Communication Designer</span>
						</div>
					</li>
					<li>
						<div class="col-md-3">
							<%= link_to (image_tag "logo/ldg.png"), root_path %>
						</div>
						<div class="col-md-9">
							<p>Prolific Interactive</p>
							<span>Mobile Product Designer</span>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="clear"></div>
		<div class="btn-foot">
			<div class="col-md-8 lside">
				<p>Copyright © 2009–2016 Dribbble LLC. All screenshots © their respective owners. Shipped from Salem, Mass. USA.</p>
				<ul class="list-inline">
					<li><a href="#"><span class="fa fa-dribbble"></span></a></li>
					<li><a href="#"><span class="fa fa-facebook-official"></span></a></li>
					<li><a href="#"><span class="fa fa-twitter"></span></a></li>
					<li><a href="#"><span class="fa fa-instagram"></span></a></li>
				</ul>
			</div>
			<div class="col-md-4 rside">
				<h4><%= Post.all.count %></h4>
				<span>pixels dribbbled</span>
			</div>
		</div>
	</div>
</footer>
</body>
</html>

app/views/posts/_form.html.haml
=simple_form_for @post do |f|
	.form-group.vbvbb.pull-right
		.img-up
			=f.input :image, label:false
		.top-side
			.sda
				%span.ho
				%p
					%a{:href => "#"} Or select from computer
		.prev
			- unless @post.image.blank?
				= image_tag @post.image.url(:medium)

	.lform.pull-left
		.form-group
			=f.input :title, placeholder: "Title", label:false
		.form-group
			=f.input :link, placeholder: "Link", label:false
		.form-group
			=f.input :description, placeholder: "Description", label:false
		.chkbx
			=f.check_box :attach
			%span Attachment
		.form-group
			=f.input :tag_list, placeholder: "Tags", label:false

		=f.button :submit, "Upload", class: "btnd"

app/views/posts/edit.html.erb
<div class="container cf2 fofo">
	<div class="title">
		<h2>Edit</h2>
	</div>
	<div class="jiform">
		<%= render 'form' %>
	</div>
</div>

app/views/posts/index.html.erb
<% if !user_signed_in? %>
	<div class="header">
		<div class="container-fluid">
			<ul class="list-inline hdr">
				<li>
					<h4>What are you working on?<span> Dribbble is show and tell for designers.</span></h4>
				</li>
				<li>
					<a href="#" class="btn btn-default btn-l">Learn more</a>
				</li>
				<li>
					<% if !user_signed_in? %>
						<a href="#" class="btn btn-default btn-s">Sign up</a>
					<% end %>
				</li>
			</ul>
		</div>
	</div>
<% end %>
<div class="categories">
	<div class="container-fluid">
		<ul class="list-inline fd">
			<% if !user_signed_in? %>
				<li><a class="sub-cat" href="#">Popular</a></li>
				<li><a class="sub-cat" href="#">Shots</a></li>
				<li><a class="sub-cat" href="#">Now</a></li>
			<% else %>
				<li><a href="#">Following</a></li>
				<li><a href="#">Suggestions</a></li>
			<% end %>
		</ul>
	</div>
</div>
<div class="main-content">
	<div class="container-fluid cf2">
		<div class="row">
			<% @posts.each do |post| %>
				<div class="col-sm-6 col-md-2 frm">
					<div class="thumbnail tmbl">
						<div class="img-co">
							<%= link_to (image_tag post.image.url(:thumb)), post %>
						</div>
						<ul class="list-inline pull-right">
							<li>
								<span class="like"><%= post.get_upvotes.size %></span>
							</li>
							<li>
								<span class="comm"><%= post.comments.count %></span>
							</li>
							<li>
								<span class="view"><%= post.impression_count %></span>
							</li>
						</ul>
						<% if post.attach? %>
						<ul class="list-inline pull-left">
							<li>
								<span class="att"></span>
							</li>
						</ul>
						<% end %>
						<div class="clear"></div>
					</div>
					<%= link_to(post_path(post)) do %>
						<div class="hov">
							<div class="cons">
								<span class="title"><%= truncate(post.title, length: 20) %></span>
								<p class="cox"><%= truncate(post.description, length: 90) %></p>
								<span class="date"><%= post.created_at.strftime('%B %e, %G') %></span>
							</div>
						</div>
					<% end %>
					<div class="designer">
						<% if post.user.profile? %>
							<%= link_to dashboard_path(post.user.id), class: "trigger" do %>
								<%= image_tag post.user.profile.url(:xssmall) %>
								<div class="tltip">
									<div class="tltip_con">
										<div class="tl_title">
											<% @postxs = Post.all.where(user_id: post.user.id).order("created_at desc").limit(4) %>
											<% @postxs.each do |pps| %>
												<div class="col-sm-3 xsd">
													<%= image_tag pps.image.url(:attach), class: "fo-img" %>
												</div>
											<% end %>
										</div>
										<div class="sot">
											<%= image_tag post.user.profile.url(:medium), class: "gfj" %>
										</div>
										<div class="clear"></div>
										<div class="vjdghs">
											<p><%= post.user.name %></p>
											<span><%= post.user.location %></span>
											<p class="ha"><%= post.user.bio %></p>
										</div>
										<div class="mnsg">
											<ul class="list-inline">
												<li>20 <span>Shots</span></li>
												<li>2897 <span>Follower</span></li>
											</ul>
										</div>
									</div>
								</div>
							<% end %>
						<% else %>
							<%= link_to image_tag "logo/ava.gif", class: "hdgt trigger" %>
						<% end %>
						<span><%= link_to post.user.name, dashboard_path(post.user.id) %></span>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="cf">
		<%= will_paginate @posts %>
	</div>
</div>

app/views/posts/maxshow.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>dribclone</title>
	<%= stylesheet_link_tag    'maxshow', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
	<div class="container-fluid gogos">
		<div class="titleg">
			<%= link_to image_tag("logo/sign_in_lg.png"), root_path, class: "navbar-default" %>
			<span class="sep"></span>
			<p><%= link_to @post.title %></p>
			<span class="bcgd">by <%= @post.user.name %> <span class="fa fa-eye"></span><%= @post.impression_count %> views</span>
		</div>
		<div class="maij-co">
			<div class="coj">
				<%= image_tag @post.image.url %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/posts/maxshow.js.erb
$("#myModal").html("<%= escape_javascript(render 'post/maxshow') %>");

app/views/posts/new.html.erb
<div class="container cf2 fofo">
	<div class="title">
		<h2>Shots</h2>
	</div>
	<div class="jiform">
		<%= render 'form' %>
	</div>
</div>

app/views/posts/register_info.html.erb
<div class="main-warp">
	<div class="heros">
		<div class="hero-title">
		<div class="lft-tit">
			<h5>JOIN THE DRIBBBLE COMMUNITY</h5>
			<h1>Sign Up</h1>
		</div>
		<div class="btn-hj">
			<a href="#" class="btn-ques">
				<p>Questions?</p>
				<span>Visit our Help Center</span>
			</a>
		</div>
		</div>
	</div>
	<div class="main-cons">
		<div class="contain">
			<div class="titles">
				<h4>Dribbble is a show and tell community for designers</h4>
				<p>
					Sign up to find, follow and hire members of our small but vibrant community of designers, icon artists, illustrators, interface designers, typographers, and other creative folks.
				</p>
			</div>
			<div class="tbs">
				<div class="col-md-4">
					<div class="tui">
						<span class="bsc">Basic</span>
					</div>
					<ul>
						<li>Follow your favorite designers and design teams</li>
						<li>Like and organize your favorite shots</li>
						<li>Limited messaging to designers about work opportunities</li>
					</ul>
					<div class="status">
						<p class="jk">Free</p>
						<%= link_to "Sign up", new_user_registration_path %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="tui">
						<span class="bsd">PRO</span>
					</div>
					<ul>
						<li>Find designers for hire by location, skill &amp; more</li>
						<li>Send unlimited messages to designers about work opportunities</li>
						<li>Organize your favorite designers with lists</li>
					</ul>
					<div class="status">
						<p class="jk">$20 <span>per year</span></p>
						<%= link_to "Learn more", new_user_registration_path, class: "btn-pro" %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="tui">
						<span class="bse">TEAM</span>
					</div>
					<ul>
						<li>Team members can immediately upload their work on Dribbble</li>
						<li>Promote your products and design services</li>
						<li>Hire designers</li>
					</ul>
					<div class="status">
						<p class="jk">$100 <span>per year</span></p>
						<%= link_to "Learn more", new_user_registration_path, class: "btn-team" %>
					</div>
				</div>
			</div>
		</div>
		<div class="rht">
			<h4>How do designers share work?</h4>
			<p class="copy">Uploading design work and commenting on the work of others <a href="#">requires an invitation</a> from a member of our community.</p><br>
			<p class="copy">See our <a href="#">Help Center</a> for information on how invitations work.</p>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="main-page">
	<div class="container cfd">
		<div class="show-title">
			<div class="img-ico">
				<% if @post.user.profile? %>
					<%= link_to (image_tag @post.user.profile.url(:thumb), class: "img-h"), root_path %>
				<% else %>
					<%= link_to (image_tag "logo/vtl_013_08.jpg", class: "img-h"), root_path %>
				<% end %>
			</div>
			<div class="ftit">
				<h3><%= @post.title %></h3>
				<p>by <span><%= link_to @post.user.name, root_path %></span> on <span><%= @post.created_at.strftime('%b %e, %G') %></span></p>
			</div>
		</div>
		<div class="main-scon">
			<div class="lft-sd">
				<div class="img-fr">
					<%= image_tag @post.image.url(:medium) %>
					<% if @post.attach? %>
						<div class="atch">
							<p><i class="fa fa-paperclip"></i>ATTACHMENT</p>
							<%= link_to (image_tag @post.image.url(:attach)), maxshow_post_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'}  %>
						</div>
					<% end %>
				</div>
				<div class="desc">
					<p><%= @post.description %></p>
				</div>
				<hr>
				<div class="cmns">
					<h5><%= pluralize(@post.comments.count, "Responses") %></h5>
					<ul>
						<% @comments.each do |comment| %>
							<li>
								<div class="names">
									<div class="ig">
										<%= link_to post_path do %>
											<% if @post.user.profile? %>
												<%= image_tag(comment.user.profile.url(:small)) %>
											<% else %>
												<%= image_tag("logo/vtl_013_08.jpg") %>
											<% end %>
											<p><%= comment.user.name %></p>
										<% end %>
									</div>
								</div>
								<div class="coms">
									<p><%= comment.content %></p>
									<span>about <%= time_ago_in_words(comment.created_at) %> ago</span>
								</div>
							</li>
						<% end %>
					</ul>
					<% if user_signed_in? %>
						<div class="com-frm">
							<%= render 'comments/form' %>
						</div>
					<% end %>
				</div>
			</div>
			<div class="rgt-side">
				<div class="vws">
					<span class="fa fa-eye"></span><span class="lk"><%= @post.impression_count %> views</span>
				</div>
				<div class="lks">
					<%= link_to like_post_path(@post), method: :get do %>
						<span class="fa fa-heart"></span>
						<span><%= @post.get_upvotes.size %> likes</span>
					<% end %>
				</div>
				<% if current_user == @post.user %>
					<div class="manage">
						<div class="edt">
							<%= link_to edit_post_path do %>
								<span class="fa fa-pencil-square-o"></span><span class="hj">edit</span>
							<% end %>
						</div>
						<div class="del">
							<%= link_to root_path, method: :delete, data: {confirm: "Are you sure?"} do %>
								<span class="fa fa-trash"></span><span class="hj">delete</span>
							<% end %>
						</div>
						<div class="clear"></div>
					</div>
				<% end %>
				<div class="rnd">
					<p>
						<%= link_to post_path do %>
							<span>More from</span>
							<span><%= @post.user.name.capitalize! %></span>
						<% end %>
					</p>
					<div class="img-rnd">
						<% @random_posts.each do |random| %>
							<div class="col-xs-6 col-md-3 xcd">
								<div class="thumbnail xsf">
									<%= link_to (image_tag random.image.url(:attach)), post_path(random) %>
								</div>
							</div>
							<span class="sp"></span>
						<% end %>
					</div>
					<div class="clear"></div>
				</div>
				<div class="vst-link">
					<%= link_to "Visit Us", @post.link, target: "blank" %>
				</div>
				<div class="tags">
					<div class="tags-c">
						<h3>Tags</h3>
						<%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(' ') %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
				<div class="modal-title" id="myModalLabel">
					<%= link_to (image_tag "logo/sign_in_lg.png"), root_path, class: "navbar-brand cvdf" %>
					<span class="sep"></span>
					<p><%= link_to @post.title %></p>
					<span class="bcgd">by <%= @post.user.name %> <span class="fa fa-eye"></span><%= @post.impression_count %> views</span>
				</div>
			</div>
			<div class="modal-body">
				<div class="pst-con">
					<%= image_tag @post.image.url %>
				</div>
			</div>
		</div>
	</div>
</div>